### ISSUE TITLE
Only exports first sheet in XML file

### ISSUE THREAD

**Issue by morfj** [languitar/drawio-batch#2]
It only exports the first diagram/page/sheet of an Draw.io XML file. 
At least for PDF export it would make sense to export every sheet as a separate page in the PDF.

**Comment by languitar** [comment]
I didn't even know that multiple sheets exist. Will have to check that.

**Comment by mainbrain** [comment]
Solved issue via --diagram parameter in my fork: https://github.com/mainbrain/drawio-batch. Will send a merge request.
