### ISSUE TITLE
Pass argument to crop only image portion of page

### ISSUE THREAD

**Issue by thexavier666** [languitar/drawio-batch#3]
Currently, the entire page is exported even if the image is tiny.
The online version has an option to crop the page so that just the image is exported.
Can we have this functionality?

**Comment by languitar** [comment]
This happens automatically if you remove the page view option in your document.

**Comment by thexavier666** [comment]
Thanks @languitar 

Those who want to disable Page View, 
 * Open the image in draw.io
 * Go to `View->Page View`
 * Untick the option
 * Save the file

Now, convert the image to pdf, it should now be properly cropped.
