### ISSUE TITLE
images draw as colored blocks

### ISSUE THREAD

**Issue by itswg** [languitar/drawio-batch#7]
Shapes that are images draw as colored blocks when run through batch processor.

![draw_io_test_drawiobatch](https://user-images.githubusercontent.com/3741929/48734534-af09f800-ec13-11e8-8424-3dfed392cf7d.png)

Exporting directly from application renders images properly.
![draw_io_test_exported](https://user-images.githubusercontent.com/3741929/48734535-af09f800-ec13-11e8-8ae2-029d96a7ebdd.png)

original document (remove ".txt" )
[draw_io_test.xml.txt](https://github.com/languitar/drawio-batch/files/2597017/draw_io_test.xml.txt)

**Comment by itswg** [comment]
@languitar, not sure if you get notified automatically or if just when called out.

**Comment by languitar** [comment]
Interesting, I have no idea what is going on there and how such images are maintained by drawio. Will take some time to debug this.

**Comment by itswg** [comment]
Thank you.  I wasn't able to go deep on debugging it myself in the nodejs environment.

**Comment by languitar** [comment]
After a quick look I am also puzzled what is happening here. However, I might have to do some serious restructuring to the code anyway as it seems that picture generation has changed a lot upstream now. Might take some more time.

**Comment by languitar** [comment]
CORS was the issue, which prevented the external images from being loaded.

**Comment by itswg** [comment]
Thank you!
This was a big improvement.  Strangely, one of the images in your test still fails (the gray box).

![test](https://user-images.githubusercontent.com/3741929/50702896-49859580-1020-11e9-8f6e-a2feed622fce.png)

Thanks for your time on the issue.

**Comment by languitar** [comment]
Interesting. Do you know where that shape comes from? I can't find it in the drawio library.

**Comment by languitar** [comment]
This still seems to be another facet of CORS. I think that image from AWS3D needs a custom javascript function for rendering correctly. However, somehow, despite adding some flags, chromium refuses to load the script for file:// uris.

**Comment by itswg** [comment]
Interesting....
I just grabbed a bunch of AWS shapes.
It's strange that some load, but not others.  Why would this one be a file:// uri?  What are the others?

**Comment by languitar** [comment]
Internally, I use the webpage that also drawio online uses for rendering the images. But in my case, it is served from file systems and in that case usually browsers prevent fetching resources from different origins. But I don't fully understand why this applies here and only for the executable code.
